[package]
name = "rust_api"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
mongodb = "2.8"
jsonwebtoken = "8"
bcrypt = "0.15"
chrono = { version = "0.4", features = ["serde"] }
env_logger = "0.10"
rand = "0.8"